apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpserve
  name: httpserve
  namespace: http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpserve
  template:
    metadata:
      labels:
        app: httpserve
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
      - name: httpserve
        image: sweetbreeze0207/httpserver
        imagePullPolicy: IfNotPresent  
        ports:
          - containerPort: 80
        volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
        resources:
          limits:
            cpu: "700m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "200Mi"
---
# Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpserve
  name: httpserve
spec:
  selector:
    app: httpserve
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
# ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpserve
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - serve.kubemaster.io
      secretName: httpserve-tls
  rules:
  - host: serve.kubemaster.io
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: httpserve
            port:
              number: 80

